apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "demo-template"
  annotations:
    "humanitec.com/orgId": "blueally-test"
    "humanitec.com/appId": "demo-template"
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
